pr:
#- master
#- test
#- develop
- projectFiles

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "1.8"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: "/jdk-8u241-linux-x64.tar.gz"
      jdkDestinationDirectory: "/builds/binaries/externals"
      cleanDestinationDirectory: true
      
- task: Maven@3
  inputs:
    mavenPomFile: 'Blankmon/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test'
